name: ğŸš€ Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ï¿½ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
      
      - name: ğŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.kyakabi.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          protocol: ftp
          port: 21
          log-level: verbose

      - name: ğŸ–¥ï¸ Run commands on server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: projects.kyakabi.com
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/kyakabic/projects.kyakabi.com/
            php artisan optimize:clear
            php artisan view:cache
            php artisan route:cache
